name: 'Setup Flutter'
description: 'Setup Flutter environment and dependencies'

inputs:
  flutter-version:
    description: 'Flutter version to use'
    required: true
    default: '3.29.2'
  google-service-json:
    description: 'Base64 encoded Google Services JSON'
    required: true
  env-file-content:
    description: 'Base64 encoded ENV file content'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ inputs.flutter-version }}

    - name: Install dependencies
      shell: bash
      run: flutter pub get

    - name: copy google-service
      shell: bash
      run: echo "${{ inputs.google-service-json }}" | base64 --decode --ignore-garbage > ./android/app/google-services.json

    - name: copy .env
      shell: bash
      run: echo "${{ inputs.env-file-content }}" | base64 --decode --ignore-garbage > ./.env

