name: "Setup Flutter"
description: "Setup Flutter environment and dependencies"

inputs:
  flutter-version:
    description: "Flutter version to use"
    required: true
    default: "3.41.8"
  google-service-json:
    description: "Base64 encoded Google Services JSON"
    required: true
  env-file-content:
    description: "Base64 encoded ENV file content"
    required: true
  firebase-json:
    description: "Base64 encoded Firebase JSON"
    required: false
    default: null
  key_properties:
    description: "Base64 encoded key.properties"
    required: true
  jks:
    description: "Base64 encoded .jks"
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ inputs.flutter-version }}

    - name: Install dependencies
      shell: bash
      run: flutter pub get

    - name: copy google-service
      shell: bash
      run: echo "${{ inputs.google-service-json }}" | base64 --decode --ignore-garbage
        > ./android/app/google-services.json

    - name: copy .env
      shell: bash
      run: echo "${{ inputs.env-file-content }}" | base64 --decode --ignore-garbage >
        ./env

    - name: copy firebase.json
      if: inputs.firebase-json != '' && inputs.firebase-json != 'null'
      shell: bash
      run: echo "${{ inputs.firebase-json }}" | base64 --decode --ignore-garbage >
        ./firebase.json

    - name: copy key.properties
      if: inputs.key_properties != ''
      shell: bash
      run: echo "${{ inputs.key_properties }}" | base64 --decode --ignore-garbage >
        ./android/key.properties

    - name: copy jks
      if: inputs.jks != ''
      shell: bash
      run: echo "${{ inputs.jks }}" | base64 --decode --ignore-garbage >
        ./android/app/akita_release.jks
