name: Build and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: flutter pub get

      - name: Setup Google Services JSON
        run: |
          echo "${{ secrets.GOOGLE_SERVICES_JSON }}" | base64 -d > android/app/google-services.json
        shell: bash

      - name: Build the app
        run: flutter build apk

      - name: Deploy to Firebase
        uses: wzieba/firebase-action@v1
        with:
          action: deploy
          projectId: ${{ secrets.FIREBASE_PROJECT_ID }}